#!/bin/env bash
# This is a fake shebang for vim highlights!

exec --no-startup-id export GTK_IM_MODULE=fcitx
exec --no-startup-id export XMODIFIERS=@im=fcitx
exec --no-startup-id export QT_IM_MODULE=fcitx
exec --no-startup-id export SDL_IM_MODULE=fcitx
exec --no-startup-id export DESKTOP_SESSION=sway
exec xrdb -load ~/.Xdefaults
