#!/usr/bin/bash
pos_x=$(xrandr | rg primary | awk '{split($4,arr,"+");print arr[2]}')
pos_y=$(xrandr | rg primary | awk '{split($4,arr,"+");print arr[3]}')
if [ $(pgrep "stalonetray") ]; then
    killall -q stalonetray
else
    exec stalonetray --geometry 1x1+$((pos_x+2))+$((pos_y+64))
fi
