actions:
  lns: ln -sf {0} {1}
config:
  backup: true
  create: true
  dotpath: dotfiles
  import_variables:
  - profiles.d/common.var.yaml
dotfiles:
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
    template: true
  f_zshrc:
    src: shell/zshrc
    dst: ~/.zshrc
  f_zshenv:
    src: shell/zshenv
    dst: ~/.zshenv
  f_zprofile:
    src: shell/zprofile
    dst: ~/.zprofile
  d_fish:
    src: shell/fish
    dst: ~/.config/fish
    chmod: '644'
  d_tmux:
    src: shell/tmux
    dst: ~/.config/tmux
    actions:
    - lns "~/.config/tmux/tmux.conf" "~/.tmux.conf"
    upignore:
    - plugins
    - plugins/*
  f_xresources:
    src: desktop/Xresources
    dst: ~/.Xresources
  f_xinitrc:
    src: desktop/xinitrc
    dst: ~/.xinitrc
  d_i3:
    src: desktop/i3
    dst: ~/.config/i3
  d_sway:
    src: desktop/sway
    dst: ~/.config/sway
  d_picom:
    src: desktop/picom
    dst: ~/.config/picom
  d_polybar:
    src: desktop/polybar/blocks
    dst: ~/.config/polybar/blocks
  d_waybar:
    src: desktop/waybar
    dst: ~/.config/waybar
  d_swaylock:
    src: desktop/swaylock
    dst: ~/.config/swaylock
  f_stalonetrayrc:
    src: desktop/stalonetrayrc
    dst: ~/.stalonetrayrc
  f_betterlockscreenrc:
    src: desktop/betterlockscreenrc
    dst: ~/.config/betterlockscreenrc
  d_wallpapers_meumy:
    src: desktop/appearance/Wallpapers/Meumy
    dst: ~/Pictures/Wallpapers/Meumy
  d_icons:
    src: desktop/appearance/icons
    dst: ~/.icons
    chmod: '644'
  f_fehbg:
    src: desktop/appearance/fehbg
    dst: ~/.fehbg
    chmod: '755'
  d_merry_cursors:
    src: desktop/appearance/merry_cursors
    dst: ~/.local/share/icons/merry_cursors
  d_gtk-3.0:
    src: desktop/appearance/gtk-3.0
    dst: ~/.config/gtk-3.0
    chmod: '644'
  f_gtkrc-2.0:
    src: desktop/appearance/gtkrc-2.0
    dst: ~/.gtkrc-2.0
  f_xsettingsd:
    src: desktop/appearance/xsettingsd
    dst: ~/.xsettingsd
  d_alacritty:
    src: terminal/alacritty
    dst: ~/.config/alacritty
  d_nvim:
    src: nvim
    dst: ~/.config/nvim
    upignore:
    - '*'
    cmpignore:
    - '*'
  f_offlineimap.py:
    src: mail/offlineimap.py
    dst: ~/.offlineimap.py
  f_offlineimaprc:
    src: mail/offlineimaprc
    dst: ~/.offlineimaprc
  d_aerc:
    src: mail/aerc
    dst: ~/.config/aerc
  f_aerc.desktop:
    src: mail/aerc.desktop
    dst: ~/.local/share/applications/aerc.desktop
  d_imapnotify:
    src: mail/imapnotify
    dst: ~/.config/imapnotify
  d_zathura:
    src: applications/zathura
    dst: ~/.config/zathura
  f_nnn.desktop:
    src: applications/nnn/nnn.desktop
    dst: ~/.local/share/applications/nnn.desktop
  d_xdg-desktop-portal-termfilechooser:
    src: applications/nnn/xdg-desktop-portal-termfilechooser
    dst: ~/.config/xdg-desktop-portal-termfilechooser
  d_mpv:
    src: applications/mpv
    dst: ~/.config/mpv
    chmod: '644'
    upignore:
    - watch_later
    - watch_later/*
  d_onedrive:
    src: applications/onedrive
    dst: ~/.config/onedrive
    upignore:
    - '!config'
    - '!sync_list'
    - '[a-zA-Z0-9.\-]*'
  d_custom_scripts:
    src: scripts
    dst: ~/.local/bin/custom_scripts
    actions:
    - lns '~/.local/bin/custom_scripts/*' '~/.local/bin/'
    chmod: '755'
  d_dunst:
    src: applications/dunst
    dst: ~/.config/dunst
  d_rofi:
    src: applications/rofi
    dst: ~/.config/rofi
  f_config.yaml:
    src: desktop/appearance/darkman/config.yaml
    dst: ~/.config/darkman/config.yaml
  d_light-mode.d:
    src: desktop/appearance/darkman/light-mode.d
    dst: ~/.local/share/light-mode.d
    chmod: '755'
  d_dark-mode.d:
    src: desktop/appearance/darkman/dark-mode.d
    dst: ~/.local/share/dark-mode.d
    chmod: '755'
profiles:
  ltrumpArch:
    dotfiles:
    - ALL
  server:
    dotfiles:
    - d_fish
    - d_tmux
    - d_custom_scripts
