#!/bin/bash
swaymsg -t subscribe -m '[ "window" ]' | while IFS= read -r line; do
    if [[ $(echo "$line" | jq -r '.change') == 'new' ]]; then
        cur_con_id=$(echo "$line" | jq -r '.container.id')
        ws=$(swaymsg -t get_tree | jq ".. | objects | select(.type == \"workspace\" and (.nodes[0] | .id) == $cur_con_id)")
        if [[ -n "$ws" ]]; then
            swaymsg [con_id="$cur_con_id"] layout toggle split, layout toggle split
        fi
    fi
done
